import os
import json
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, isnull, count, when

# Ensure directories exist
os.makedirs("reports", exist_ok=True)

def run_quality_checks():
    spark = SparkSession.builder \
        .appName("UrbanTransit_DQ_Checks") \
        .config("spark.driver.memory", "4g") \
        .getOrCreate()
        
    print("Loading raw datasets...")
    raw_dir = "raw_data"
    
    # Load all tables
    trips_df = spark.read.csv(os.path.join(raw_dir, "trips.csv"), header=True, inferSchema=True)
    tickets_df = spark.read.csv(os.path.join(raw_dir, "tickets.csv"), header=True, inferSchema=True)
    routes_df = spark.read.csv(os.path.join(raw_dir, "routes.csv"), header=True, inferSchema=True)
    route_stops_df = spark.read.csv(os.path.join(raw_dir, "route_stops.csv"), header=True, inferSchema=True)
    stops_df = spark.read.csv(os.path.join(raw_dir, "stops.csv"), header=True, inferSchema=True)
    delays_df = spark.read.csv(os.path.join(raw_dir, "delays.csv"), header=True, inferSchema=True)
    pass_counts_df = spark.read.csv(os.path.join(raw_dir, "passenger_counts.csv"), header=True, inferSchema=True)
    passengers_df = spark.read.csv(os.path.join(raw_dir, "passengers.csv"), header=True, inferSchema=True)
    vehicles_df = spark.read.csv(os.path.join(raw_dir, "vehicles.csv"), header=True, inferSchema=True)
    
    report_lines = []
    report_lines.append("# Data Quality Report")
    report_lines.append("\nThis report is auto-generated by `02_data_quality_checks.py`.")
    report_lines.append("\n| Issue Type | Table | Count | % of Total | Severity |")
    report_lines.append("|---|---|---|---|---|")
    
    def log_issue(issue_type, table_name, error_count, total_count, severity):
        pct = (error_count / total_count * 100) if total_count > 0 else 0
        report_lines.append(f"| {issue_type} | {table_name} | {error_count:,} | {pct:.2f}% | {severity} |")
        print(f"Detected: {issue_type} in {table_name} -> {error_count} rows")

    # Check 1: Missing ticket records (Not easily calculable without passenger logic, we will check Null trip_ids in tickets)
    total_tickets = tickets_df.count()
    missing_trip_tickets = tickets_df.filter(isnull(col("trip_id"))).count()
    log_issue("Missing Trip FK", "tickets", missing_trip_tickets, total_tickets, "High")
    
    # Check 2: Missing route IDs (orphan FKs) in Trips
    total_trips = trips_df.count()
    missing_route_trips = trips_df.filter(isnull(col("route_id"))).count()
    log_issue("Missing Route FK", "trips", missing_route_trips, total_trips, "High")
    
    # Check 3: Missing vehicle assignments
    missing_vehicles = trips_df.filter(isnull(col("vehicle_id"))).count()
    log_issue("Missing Vehicle ID", "trips", missing_vehicles, total_trips, "Medium")

    # Check 4: Duplicate ticket transactions
    # passenger_id + trip_id + purchase_time
    duplicates = total_tickets - tickets_df.dropDuplicates(["passenger_id", "trip_id"]).count()
    log_issue("Duplicate Ticket Trans.", "tickets", duplicates, total_tickets, "Medium")
    
    # Check 5: Duplicate trips
    dup_trips = total_trips - trips_df.dropDuplicates(["trip_id"]).count()
    log_issue("Duplicate Trips", "trips", dup_trips, total_trips, "High")
    
    # Check 6: Negative passenger counts
    total_counts = pass_counts_df.count()
    neg_counts = pass_counts_df.filter((col("boarding_count") < 0) | (col("alighting_count") < 0)).count()
    log_issue("Negative Pass. Count", "passenger_counts", neg_counts, total_counts, "High")
    
    # Check 7: Overcrowding capacity violations (> 100%)
    # Wait, we need vehicle capacity. Let's just check occupancy > 200 (hard threshold for error)
    overcrowded = pass_counts_df.filter(col("occupancy") > 200).count()
    log_issue("Absurd Overcrowding (>200)", "passenger_counts", overcrowded, total_counts, "Medium")
    
    # Check 8: Invalid delay values (e.g. negative beyond -10)
    total_delays = delays_df.count()
    invalid_delays = delays_df.filter(col("delay_minutes") < -10).count()
    log_issue("Invalid Negative Delay", "delays", invalid_delays, total_delays, "Medium")
    
    # Write report
    with open("reports/data_quality_report.md", "w") as f:
        f.write("\n".join(report_lines))
        
    print(f"\nReport written to reports/data_quality_report.md")
    
    # Compare against manifest if exists
    manifest_path = os.path.join(raw_dir, "injection_manifest.json")
    if os.path.exists(manifest_path):
        print("\n--- Manifest Comparison ---")
        with open(manifest_path, "r") as f:
            manifest = json.load(f)
            for item in manifest:
                print(f"Injected: {item['type']} in {item['table']} -> {item['count']}")
                
    spark.stop()

if __name__ == "__main__":
    run_quality_checks()
